gcloud compute instances create-with-container walrus-1 --project=prancingwalrus --zone=us-central1-a \
  --machine-type=e2-micro --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default \
  --maintenance-policy=MIGRATE --provisioning-model=STANDARD \
  --service-account=walrus-sheet-access@prancingwalrus.iam.gserviceaccount.com \
  --scopes=https://www.googleapis.com/auth/cloud-platform \
  --image=projects/cos-cloud/global/images/cos-stable-109-17800-66-54 --boot-disk-size=10GB \
  --boot-disk-type=pd-standard --boot-disk-device-name=walrus-1 \
  --container-image=us-central1-docker.pkg.dev/prancingwalrus/prancing-walrus/prancing-walrus:v0.03 \
  --container-restart-policy=always --container-env=BOT_TOKEN=<bot token here>,APIKey=<sheets api key here> \
  --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring \
  --labels=goog-ec-src=vm_add-gcloud,container-vm=cos-stable-109-17800-66-54