tasks:
  - name: Terminal
    # before always runs first
    before: ./gitpodconfig/tasks/before.sh
    # init only runs on initial workspace creation
    init: ./gitpodconfig/tasks/init.sh
    # command runs at every workspace startup
    command: ./gitpodconfig/tasks/command.sh


image:
    file: .gitpod.Dockerfile

additionalRepositories:
  - url: https://github.com/delve/sheetdb.git
    checkoutLocation: sheetdb
  - url: https://github.com/delve/gsheets.git
    checkoutLocation: gsheets

workspaceLocation: prancing-walrus/main.code-workspace