// Code generated by "sheetdb-modeler"; DO NOT EDIT.
// Create a Spreadsheet (sheet name: "clubs") as data storage.
// The spreadsheet header is as follows:
//   club_id | name | abrv | updated_at | deleted_at
// Please copy and paste this header on the first line of the sheet.

package sheetDAO

import (
	"strconv"
	"sync"
	"time"

	"github.com/delve/gsheets"
	"github.com/delve/sheetdb"
)

const (
	// Sheet definition
	_Club_sheetName        = "clubs"
	_Club_column_ClubID    = 0 // A
	_Club_column_Name      = 1 // B
	_Club_column_Abrv      = 2 // C
	_Club_column_UpdatedAt = 3 // D
	_Club_column_DeletedAt = 4 // E
)

var (
	_Club_mutex          = sync.RWMutex{}
	_Club_cache          = map[int]*Club{} // map[clubID]*Club
	_Club_rowNoMap       = map[int]int{}   // map[clubID]rowNo
	_Club_maxRowNo       = 0
	_Club_Name_uniqueMap = map[string]*Club{} // map[name]*Club
	_Club_Abrv_uniqueMap = map[string]*Club{} // map[abrv]*Club
)

func init() {
	sheetdb.RegisterModel("default", "Club", _Club_sheetName, _Club_load)
}

func _Club_load(data *gsheets.Sheet) error {

	_Club_mutex.Lock()
	defer _Club_mutex.Unlock()

	_Club_cache = map[int]*Club{}
	_Club_rowNoMap = map[int]int{}
	_Club_maxRowNo = 0
	_Club_Name_uniqueMap = map[string]*Club{}
	_Club_Abrv_uniqueMap = map[string]*Club{}

	for i, r := range data.Rows() {
		if i == 0 {
			continue
		}
		if r.Value(_Club_column_DeletedAt) != "" {
			_Club_maxRowNo++
			continue
		}
		if r.Value(_Club_column_ClubID) == "" {
			break
		}

		clubID, err := _Club_parseClubID(r.Value(_Club_column_ClubID))
		if err != nil {
			return err
		}
		name := r.Value(_Club_column_Name)
		if err := _Club_validateName(name, ""); err != nil {
			return err
		}
		abrv := r.Value(_Club_column_Abrv)
		if err := _Club_validateAbrv(abrv, ""); err != nil {
			return err
		}

		if _, ok := _Club_cache[clubID]; ok {
			return &sheetdb.DuplicationError{FieldName: "ClubID"}
		}

		club := Club{
			ClubID: clubID,
			Name:   name,
			Abrv:   abrv,
		}

		_Club_maxRowNo++
		_Club_cache[club.ClubID] = &club
		_Club_rowNoMap[club.ClubID] = _Club_maxRowNo
		_Club_Name_uniqueMap[club.Name] = &club
		_Club_Abrv_uniqueMap[club.Abrv] = &club
	}

	return nil
}

// GetClub returns a club by ClubID.
// If it can not be found, this function returns *sheetdb.NotFoundError.
func GetClub(clubID int) (*Club, error) {
	_Club_mutex.RLock()
	defer _Club_mutex.RUnlock()
	if v, ok := _Club_cache[clubID]; ok {
		return v, nil
	}
	return nil, &sheetdb.NotFoundError{Model: "Club"}
}

// GetClubByName returns a club by Name.
// If it can not be found, this function returns *sheetdb.NotFoundError.
func GetClubByName(name string) (*Club, error) {
	_Club_mutex.RLock()
	defer _Club_mutex.RUnlock()
	if v, ok := _Club_Name_uniqueMap[name]; ok {
		return v, nil
	}
	return nil, &sheetdb.NotFoundError{Model: "Club"}
}

// GetClubByAbrv returns a club by Abrv.
// If it can not be found, this function returns *sheetdb.NotFoundError.
func GetClubByAbrv(abrv string) (*Club, error) {
	_Club_mutex.RLock()
	defer _Club_mutex.RUnlock()
	if v, ok := _Club_Abrv_uniqueMap[abrv]; ok {
		return v, nil
	}
	return nil, &sheetdb.NotFoundError{Model: "Club"}
}

// ClubQuery is used for selecting clubs.
type ClubQuery struct {
	filter func(club *Club) bool
	sort   func(clubs []*Club)
}

// ClubQueryOption is an option to change the behavior of ClubQuery.
type ClubQueryOption func(query *ClubQuery) *ClubQuery

// ClubFilter is an option to change the filtering behavior of ClubQuery.
func ClubFilter(filterFunc func(club *Club) bool) func(query *ClubQuery) *ClubQuery {
	return func(query *ClubQuery) *ClubQuery {
		if query != nil {
			query.filter = filterFunc
		}
		return query
	}
}

// ClubSort is an option to change the sorting behavior of ClubQuery.
func ClubSort(sortFunc func(clubs []*Club)) func(query *ClubQuery) *ClubQuery {
	return func(query *ClubQuery) *ClubQuery {
		if query != nil {
			query.sort = sortFunc
		}
		return query
	}
}

// GetClubs returns all clubs.
// If any options are specified, the result according to the specified option is returned.
// If there are no club to return, this function returns an nil array.
// If the sort option is not specified, the order of clubs is random.
func GetAllClubs(opts ...ClubQueryOption) ([]*Club, error) {
	query := &ClubQuery{}
	for _, opt := range opts {
		query = opt(query)
	}
	_Club_mutex.RLock()
	defer _Club_mutex.RUnlock()
	var clubs []*Club
	if query.filter != nil {
		for _, v := range _Club_cache {
			if query.filter(v) {
				clubs = append(clubs, v)
			}
		}
	} else {
		for _, v := range _Club_cache {
			clubs = append(clubs, v)
		}
	}
	if query.sort != nil {
		query.sort(clubs)
	}
	return clubs, nil
}

// AddClub adds new club.
// ClubID is generated automatically.
// If any fields are invalid, this function returns error.
func AddClub(name string, abrv string) (*Club, error) {
	_Club_mutex.Lock()
	defer _Club_mutex.Unlock()
	if err := _Club_validateName(name, ""); err != nil {
		return nil, err
	}
	if err := _Club_validateAbrv(abrv, ""); err != nil {
		return nil, err
	}
	club := &Club{
		ClubID: _Club_maxRowNo + 1,
		Name:   name,
		Abrv:   abrv,
	}
	if err := club._asyncAdd(_Club_maxRowNo + 1); err != nil {
		return nil, err
	}
	_Club_maxRowNo++
	_Club_cache[club.ClubID] = club
	_Club_rowNoMap[club.ClubID] = _Club_maxRowNo
	_Club_Name_uniqueMap[club.Name] = club
	_Club_Abrv_uniqueMap[club.Abrv] = club
	return club, nil
}

// UpdateClub updates club.
// If it can not be found, this function returns *sheetdb.NotFoundError.
// If any fields are invalid, this function returns error.
func UpdateClub(clubID int, name string, abrv string) (*Club, error) {
	_Club_mutex.Lock()
	defer _Club_mutex.Unlock()
	club, ok := _Club_cache[clubID]
	if !ok {
		return nil, &sheetdb.NotFoundError{Model: "Club"}
	}
	if err := _Club_validateName(name, club.Name); err != nil {
		return nil, err
	}
	if err := _Club_validateAbrv(abrv, club.Abrv); err != nil {
		return nil, err
	}
	clubCopy := *club
	clubCopy.Name = name
	clubCopy.Abrv = abrv
	if err := (&clubCopy)._asyncUpdate(); err != nil {
		return nil, err
	}
	if clubCopy.Name != club.Name {
		delete(_Club_Name_uniqueMap, club.Name)
	}
	if clubCopy.Abrv != club.Abrv {
		delete(_Club_Abrv_uniqueMap, club.Abrv)
	}
	*club = clubCopy
	_Club_Name_uniqueMap[clubCopy.Name] = &clubCopy
	_Club_Abrv_uniqueMap[clubCopy.Abrv] = &clubCopy
	return club, nil
}

// DeleteClub deletes club.
// If it can not be found, this function returns *sheetdb.NotFoundError.
func DeleteClub(clubID int) error {
	_Club_mutex.Lock()
	defer _Club_mutex.Unlock()
	club, ok := _Club_cache[clubID]
	if !ok {
		return &sheetdb.NotFoundError{Model: "Club"}
	}
	if err := club._asyncDelete(); err != nil {
		return err
	}
	delete(_Club_cache, clubID)
	delete(_Club_Name_uniqueMap, club.Name)
	delete(_Club_Abrv_uniqueMap, club.Abrv)
	return nil
}

func _Club_validateName(name string, oldName string) error {
	if name == "" {
		return &sheetdb.EmptyStringError{FieldName: "Name"}
	}
	if name != oldName {
		if _, ok := _Club_Name_uniqueMap[name]; ok {
			return &sheetdb.DuplicationError{FieldName: "Name"}
		}
	}
	return nil
}

func _Club_validateAbrv(abrv string, oldAbrv string) error {
	if abrv == "" {
		return &sheetdb.EmptyStringError{FieldName: "Abrv"}
	}
	if abrv != oldAbrv {
		if _, ok := _Club_Abrv_uniqueMap[abrv]; ok {
			return &sheetdb.DuplicationError{FieldName: "Abrv"}
		}
	}
	return nil
}

func _Club_parseClubID(clubID string) (int, error) {
	v, err := strconv.Atoi(clubID)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "ClubID", Err: err}
	}
	return v, nil
}

func (m *Club) _asyncAdd(rowNo int) error {
	data := []gsheets.UpdateValue{
		{
			SheetName: _Club_sheetName,
			RowNo:     rowNo,
			Values: []interface{}{
				m.ClubID,
				m.Name,
				m.Abrv,
				time.Now().UTC(),
				"",
			},
		},
	}
	return dbClient.AsyncUpdate(data)
}

func (m *Club) _asyncUpdate() error {
	data := []gsheets.UpdateValue{
		{
			SheetName: _Club_sheetName,
			RowNo:     _Club_rowNoMap[m.ClubID],
			Values: []interface{}{
				m.ClubID,
				m.Name,
				m.Abrv,
				time.Now().UTC(),
				"",
			},
		},
	}
	return dbClient.AsyncUpdate(data)
}

func (m *Club) _asyncDelete() error {
	now := time.Now().UTC()
	data := []gsheets.UpdateValue{
		{
			SheetName: _Club_sheetName,
			RowNo:     _Club_rowNoMap[m.ClubID],
			Values: []interface{}{
				m.ClubID,
				m.Name,
				m.Abrv,
				now,
				now,
			},
		},
	}
	return dbClient.AsyncUpdate(data)
}
