// Code generated by "sheetdb-modeler"; DO NOT EDIT.
// Create a Spreadsheet (sheet name: "snails") as data storage.
// The spreadsheet header is as follows:
//   snail_id | disco_id | game_name | club | server | server_num | updated_at | deleted_at
// Please copy and paste this header on the first line of the sheet.

package sheetDAO

import (
	"strconv"
	"sync"
	"time"

	"github.com/delve/gsheets"
	"github.com/delve/sheetdb"
)

const (
	// Sheet definition
	_Snail_sheetName        = "snails"
	_Snail_column_SnailID   = 0 // A
	_Snail_column_DiscoId   = 1 // B
	_Snail_column_GameName  = 2 // C
	_Snail_column_Club      = 3 // D
	_Snail_column_Server    = 4 // E
	_Snail_column_ServerNum = 5 // F
	_Snail_column_UpdatedAt = 6 // G
	_Snail_column_DeletedAt = 7 // H

	// Parent children relation for compile check
	_Snail_child_SnailStat     = 0
	_Snail_numOfChildren       = 1
	_Snail_numOfDirectChildren = 1
)

var (
	_Snail_mutex             = sync.RWMutex{}
	_Snail_cache             = map[int]*Snail{} // map[snailID]*Snail
	_Snail_rowNoMap          = map[int]int{}    // map[snailID]rowNo
	_Snail_maxRowNo          = 0
	_Snail_DiscoId_uniqueMap = map[string]*Snail{} // map[discoID]*Snail
)

func _() {
	// An "undeclared name" compiler error signifies that parent and child model set names are different.
	// Make sure that all models in parent-child relationship exist in the same model set (spreadsheet) and try again.
	_ = _SnailStat_modelSetName_default
	// An "undeclared name" compiler error signifies that parent-children option conflicts between models.
	// Make sure that the parent-children options are correct for all relevant models and try again.
	_ = _SnailStat_parent_Snail
	// An "invalid array index" compiler error signifies that the children option is incorrect.
	// Make sure that all child models are specified, including not only the direct child model
	// but also the grandchild model, and try again.
	var x [1]struct{}
	_ = x[_Snail_numOfChildren-_Snail_numOfDirectChildren-_SnailStat_numOfChildren]
}

func init() {
	sheetdb.RegisterModel("default", "Snail", _Snail_sheetName, _Snail_load)
}

func _Snail_load(data *gsheets.Sheet) error {

	_Snail_mutex.Lock()
	defer _Snail_mutex.Unlock()

	_Snail_cache = map[int]*Snail{}
	_Snail_rowNoMap = map[int]int{}
	_Snail_maxRowNo = 0
	_Snail_DiscoId_uniqueMap = map[string]*Snail{}

	for i, r := range data.Rows() {
		if i == 0 {
			continue
		}
		if r.Value(_Snail_column_DeletedAt) != "" {
			_Snail_maxRowNo++
			continue
		}
		if r.Value(_Snail_column_SnailID) == "" {
			break
		}

		snailID, err := _Snail_parseSnailID(r.Value(_Snail_column_SnailID))
		if err != nil {
			return err
		}
		discoID := r.Value(_Snail_column_DiscoId)
		if err := _Snail_validateDiscoId(discoID, ""); err != nil {
			return err
		}
		gameName := r.Value(_Snail_column_GameName)
		if err := _Snail_validateGameName(gameName); err != nil {
			return err
		}
		club := r.Value(_Snail_column_Club)
		if err := _Snail_validateClub(club); err != nil {
			return err
		}
		server, err := _Snail_parseServer(r.Value(_Snail_column_Server))
		if err != nil {
			return err
		}
		serverNum, err := _Snail_parseServerNum(r.Value(_Snail_column_ServerNum))
		if err != nil {
			return err
		}

		if _, ok := _Snail_cache[snailID]; ok {
			return &sheetdb.DuplicationError{FieldName: "SnailID"}
		}

		snail := Snail{
			SnailID:   snailID,
			DiscoId:   discoID,
			GameName:  gameName,
			Club:      club,
			Server:    server,
			ServerNum: serverNum,
		}

		_Snail_maxRowNo++
		_Snail_cache[snail.SnailID] = &snail
		_Snail_rowNoMap[snail.SnailID] = _Snail_maxRowNo
		_Snail_DiscoId_uniqueMap[snail.DiscoId] = &snail
	}

	return nil
}

// GetSnail returns a snail by SnailID.
// If it can not be found, this function returns *sheetdb.NotFoundError.
func GetSnail(snailID int) (*Snail, error) {
	_Snail_mutex.RLock()
	defer _Snail_mutex.RUnlock()
	if v, ok := _Snail_cache[snailID]; ok {
		return v, nil
	}
	return nil, &sheetdb.NotFoundError{Model: "Snail"}
}

// GetSnailByDiscoId returns a snail by DiscoId.
// If it can not be found, this function returns *sheetdb.NotFoundError.
func GetSnailByDiscoId(discoID string) (*Snail, error) {
	_Snail_mutex.RLock()
	defer _Snail_mutex.RUnlock()
	if v, ok := _Snail_DiscoId_uniqueMap[discoID]; ok {
		return v, nil
	}
	return nil, &sheetdb.NotFoundError{Model: "Snail"}
}

// SnailQuery is used for selecting snails.
type SnailQuery struct {
	filter func(snail *Snail) bool
	sort   func(snails []*Snail)
}

// SnailQueryOption is an option to change the behavior of SnailQuery.
type SnailQueryOption func(query *SnailQuery) *SnailQuery

// SnailFilter is an option to change the filtering behavior of SnailQuery.
func SnailFilter(filterFunc func(snail *Snail) bool) func(query *SnailQuery) *SnailQuery {
	return func(query *SnailQuery) *SnailQuery {
		if query != nil {
			query.filter = filterFunc
		}
		return query
	}
}

// SnailSort is an option to change the sorting behavior of SnailQuery.
func SnailSort(sortFunc func(snails []*Snail)) func(query *SnailQuery) *SnailQuery {
	return func(query *SnailQuery) *SnailQuery {
		if query != nil {
			query.sort = sortFunc
		}
		return query
	}
}

// GetSnails returns all snails.
// If any options are specified, the result according to the specified option is returned.
// If there are no snail to return, this function returns an nil array.
// If the sort option is not specified, the order of snails is random.
func GetSnails(opts ...SnailQueryOption) ([]*Snail, error) {
	query := &SnailQuery{}
	for _, opt := range opts {
		query = opt(query)
	}
	_Snail_mutex.RLock()
	defer _Snail_mutex.RUnlock()
	var snails []*Snail
	if query.filter != nil {
		for _, v := range _Snail_cache {
			if query.filter(v) {
				snails = append(snails, v)
			}
		}
	} else {
		for _, v := range _Snail_cache {
			snails = append(snails, v)
		}
	}
	if query.sort != nil {
		query.sort(snails)
	}
	return snails, nil
}

// AddSnail adds new snail.
// SnailID is generated automatically.
// If any fields are invalid, this function returns error.
func AddSnail(discoID string, gameName string, club string, server ServerName, serverNum int) (*Snail, error) {
	_Snail_mutex.Lock()
	defer _Snail_mutex.Unlock()
	if err := _Snail_validateDiscoId(discoID, ""); err != nil {
		return nil, err
	}
	if err := _Snail_validateGameName(gameName); err != nil {
		return nil, err
	}
	if err := _Snail_validateClub(club); err != nil {
		return nil, err
	}
	snail := &Snail{
		SnailID:   _Snail_maxRowNo + 1,
		DiscoId:   discoID,
		GameName:  gameName,
		Club:      club,
		Server:    server,
		ServerNum: serverNum,
	}
	if err := snail._asyncAdd(_Snail_maxRowNo + 1); err != nil {
		return nil, err
	}
	_Snail_maxRowNo++
	_Snail_cache[snail.SnailID] = snail
	_Snail_rowNoMap[snail.SnailID] = _Snail_maxRowNo
	_Snail_DiscoId_uniqueMap[snail.DiscoId] = snail
	return snail, nil
}

// UpdateSnail updates snail.
// If it can not be found, this function returns *sheetdb.NotFoundError.
// If any fields are invalid, this function returns error.
func UpdateSnail(snailID int, discoID string, gameName string, club string, server ServerName, serverNum int) (*Snail, error) {
	_Snail_mutex.Lock()
	defer _Snail_mutex.Unlock()
	snail, ok := _Snail_cache[snailID]
	if !ok {
		return nil, &sheetdb.NotFoundError{Model: "Snail"}
	}
	if err := _Snail_validateDiscoId(discoID, snail.DiscoId); err != nil {
		return nil, err
	}
	if err := _Snail_validateGameName(gameName); err != nil {
		return nil, err
	}
	if err := _Snail_validateClub(club); err != nil {
		return nil, err
	}
	snailCopy := *snail
	snailCopy.DiscoId = discoID
	snailCopy.GameName = gameName
	snailCopy.Club = club
	snailCopy.Server = server
	snailCopy.ServerNum = serverNum
	if err := (&snailCopy)._asyncUpdate(); err != nil {
		return nil, err
	}
	if snailCopy.DiscoId != snail.DiscoId {
		delete(_Snail_DiscoId_uniqueMap, snail.DiscoId)
	}
	*snail = snailCopy
	_Snail_DiscoId_uniqueMap[snailCopy.DiscoId] = &snailCopy
	return snail, nil
}

// DeleteSnail deletes snail and it's children snailStat.
// If it can not be found, this function returns *sheetdb.NotFoundError.
func DeleteSnail(snailID int) error {
	_Snail_mutex.Lock()
	defer _Snail_mutex.Unlock()
	_SnailStat_mutex.Lock()
	defer _SnailStat_mutex.Unlock()
	snail, ok := _Snail_cache[snailID]
	if !ok {
		return &sheetdb.NotFoundError{Model: "Snail"}
	}
	var snailStats []*SnailStat
	for _, v := range _SnailStat_cache[snailID] {
		snailStats = append(snailStats, v)
	}
	if err := snail._asyncDelete(snailStats); err != nil {
		return err
	}
	delete(_Snail_cache, snailID)
	delete(_Snail_DiscoId_uniqueMap, snail.DiscoId)
	delete(_SnailStat_cache, snailID)
	return nil
}

func _Snail_validateDiscoId(discoID string, oldDiscoId string) error {
	if discoID == "" {
		return &sheetdb.EmptyStringError{FieldName: "DiscoId"}
	}
	if discoID != oldDiscoId {
		if _, ok := _Snail_DiscoId_uniqueMap[discoID]; ok {
			return &sheetdb.DuplicationError{FieldName: "DiscoId"}
		}
	}
	return nil
}

func _Snail_validateGameName(gameName string) error {
	if gameName == "" {
		return &sheetdb.EmptyStringError{FieldName: "GameName"}
	}
	return nil
}

func _Snail_validateClub(club string) error {
	if club == "" {
		return &sheetdb.EmptyStringError{FieldName: "Club"}
	}
	return nil
}

func _Snail_parseSnailID(snailID string) (int, error) {
	v, err := strconv.Atoi(snailID)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "SnailID", Err: err}
	}
	return v, nil
}

func _Snail_parseServer(server string) (ServerName, error) {
	v, err := NewServerName(server)
	if err != nil {
		return v, &sheetdb.InvalidValueError{FieldName: "Server", Err: err}
	}
	return v, nil
}

func _Snail_parseServerNum(serverNum string) (int, error) {
	v, err := strconv.Atoi(serverNum)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "ServerNum", Err: err}
	}
	return v, nil
}

func (m *Snail) _asyncAdd(rowNo int) error {
	data := []gsheets.UpdateValue{
		{
			SheetName: _Snail_sheetName,
			RowNo:     rowNo,
			Values: []interface{}{
				m.SnailID,
				m.DiscoId,
				m.GameName,
				m.Club,
				m.Server.String(),
				m.ServerNum,
				time.Now().UTC(),
				"",
			},
		},
	}
	return dbClient.AsyncUpdate(data)
}

func (m *Snail) _asyncUpdate() error {
	data := []gsheets.UpdateValue{
		{
			SheetName: _Snail_sheetName,
			RowNo:     _Snail_rowNoMap[m.SnailID],
			Values: []interface{}{
				m.SnailID,
				m.DiscoId,
				m.GameName,
				m.Club,
				m.Server.String(),
				m.ServerNum,
				time.Now().UTC(),
				"",
			},
		},
	}
	return dbClient.AsyncUpdate(data)
}

func (m *Snail) _asyncDelete(snailStats []*SnailStat) error {
	now := time.Now().UTC()
	data := []gsheets.UpdateValue{
		{
			SheetName: _Snail_sheetName,
			RowNo:     _Snail_rowNoMap[m.SnailID],
			Values: []interface{}{
				m.SnailID,
				m.DiscoId,
				m.GameName,
				m.Club,
				m.Server.String(),
				m.ServerNum,
				now,
				now,
			},
		},
	}
	for _, v := range snailStats {
		data = append(data, gsheets.UpdateValue{
			SheetName: _SnailStat_sheetName,
			RowNo:     _SnailStat_rowNoMap[v.SnailID][v.SnailStatID],
			Values: []interface{}{
				v.SnailID,
				v.SnailStatID,
				v.Updated,
				v.Leadership,
				v.Art,
				v.Fth,
				v.Fame,
				v.Civ,
				v.Tech,
				v.Hp,
				v.Atk,
				v.Rush,
				v.Def,
				v.TotalPower,
				v.ZombieForm,
				v.DemonForm,
				v.AngelForm,
				v.MutantForm,
				v.MechaForm,
				v.DragonForm,
				v.SpeciesWarEssences,
				now,
				now,
			},
		})
	}
	return dbClient.AsyncUpdate(data)
}
