// Code generated by "sheetdb-modeler"; DO NOT EDIT.
// Create a Spreadsheet (sheet name: "snails") as data storage.
// The spreadsheet header is as follows:
//   player_id | snail_id | updated | snail_name | club | sw_kit | sw_kit_rank | server | server_num | leadership | art | fth | fame | civ | tech | hp | atk | rush | def | total_power | zombie_form | demon_form | angel_form | mutant_form | mecha_form | dragon_form | species_war_essences | minion_sim_power | updated_at | deleted_at
// Please copy and paste this header on the first line of the sheet.

package sheetDAO

import (
	"strconv"
	"sync"
	"time"

	"github.com/delve/gsheets"
	"github.com/delve/sheetdb"
)

const (
	// Sheet definition
	_Snail_sheetName                 = "snails"
	_Snail_column_PlayerID           = 0  // A
	_Snail_column_SnailID            = 1  // B
	_Snail_column_Updated            = 2  // C
	_Snail_column_SnailName          = 3  // D
	_Snail_column_Club               = 4  // E
	_Snail_column_SWKit              = 5  // F
	_Snail_column_SWKitRank          = 6  // G
	_Snail_column_Server             = 7  // H
	_Snail_column_ServerNum          = 8  // I
	_Snail_column_Leadership         = 9  // J
	_Snail_column_Art                = 10 // K
	_Snail_column_Fth                = 11 // L
	_Snail_column_Fame               = 12 // M
	_Snail_column_Civ                = 13 // N
	_Snail_column_Tech               = 14 // O
	_Snail_column_Hp                 = 15 // P
	_Snail_column_Atk                = 16 // Q
	_Snail_column_Rush               = 17 // R
	_Snail_column_Def                = 18 // S
	_Snail_column_TotalPower         = 19 // T
	_Snail_column_ZombieForm         = 20 // U
	_Snail_column_DemonForm          = 21 // V
	_Snail_column_AngelForm          = 22 // W
	_Snail_column_MutantForm         = 23 // X
	_Snail_column_MechaForm          = 24 // Y
	_Snail_column_DragonForm         = 25 // Z
	_Snail_column_SpeciesWarEssences = 26 // AA
	_Snail_column_MinionSimPower     = 27 // AB
	_Snail_column_UpdatedAt          = 28 // AC
	_Snail_column_DeletedAt          = 29 // AD

	// Parent children relation for compile check
	_Snail_modelSetName_default = 0
	_Snail_parent_Player        = 0
	_Snail_numOfChildren        = 0
	_Snail_numOfDirectChildren  = 0
)

var (
	_Snail_mutex    = sync.RWMutex{}
	_Snail_cache    = map[int]map[int]*Snail{} // map[playerID][snailID]*Snail
	_Snail_rowNoMap = map[int]map[int]int{}    // map[playerID][snailID]rowNo
	_Snail_maxRowNo = 0
)

func _() {
	// An "undeclared name" compiler error signifies that parent-children option conflicts between models.
	// Make sure that the parent-children options are correct for all relevant models and try again.
	_ = _Player_child_Snail
}

func init() {
	sheetdb.RegisterModel("default", "Snail", _Snail_sheetName, _Snail_load)
}

func _Snail_load(data *gsheets.Sheet) error {

	_Snail_mutex.Lock()
	defer _Snail_mutex.Unlock()

	_Snail_cache = map[int]map[int]*Snail{}
	_Snail_rowNoMap = map[int]map[int]int{}
	_Snail_maxRowNo = 0

	for i, r := range data.Rows() {
		if i == 0 {
			continue
		}
		if r.Value(_Snail_column_DeletedAt) != "" {
			_Snail_maxRowNo++
			continue
		}
		if r.Value(_Snail_column_PlayerID) == "" {
			break
		}

		playerID, err := _Snail_parsePlayerID(r.Value(_Snail_column_PlayerID))
		if err != nil {
			return err
		}
		snailID, err := _Snail_parseSnailID(r.Value(_Snail_column_SnailID))
		if err != nil {
			return err
		}
		updated, err := _Snail_parseUpdated(r.Value(_Snail_column_Updated))
		if err != nil {
			return err
		}
		snailName := r.Value(_Snail_column_SnailName)
		if err := _Snail_validateSnailName(snailName); err != nil {
			return err
		}
		club, err := _Snail_parseClub(r.Value(_Snail_column_Club))
		if err != nil {
			return err
		}
		sWKit := r.Value(_Snail_column_SWKit)
		if err := _Snail_validateSWKit(sWKit); err != nil {
			return err
		}
		sWKitRank, err := _Snail_parseSWKitRank(r.Value(_Snail_column_SWKitRank))
		if err != nil {
			return err
		}
		server, err := _Snail_parseServer(r.Value(_Snail_column_Server))
		if err != nil {
			return err
		}
		serverNum, err := _Snail_parseServerNum(r.Value(_Snail_column_ServerNum))
		if err != nil {
			return err
		}
		leadership, err := _Snail_parseLeadership(r.Value(_Snail_column_Leadership))
		if err != nil {
			return err
		}
		art, err := _Snail_parseArt(r.Value(_Snail_column_Art))
		if err != nil {
			return err
		}
		fth, err := _Snail_parseFth(r.Value(_Snail_column_Fth))
		if err != nil {
			return err
		}
		fame, err := _Snail_parseFame(r.Value(_Snail_column_Fame))
		if err != nil {
			return err
		}
		civ, err := _Snail_parseCiv(r.Value(_Snail_column_Civ))
		if err != nil {
			return err
		}
		tech, err := _Snail_parseTech(r.Value(_Snail_column_Tech))
		if err != nil {
			return err
		}
		hp, err := _Snail_parseHp(r.Value(_Snail_column_Hp))
		if err != nil {
			return err
		}
		atk, err := _Snail_parseAtk(r.Value(_Snail_column_Atk))
		if err != nil {
			return err
		}
		rush, err := _Snail_parseRush(r.Value(_Snail_column_Rush))
		if err != nil {
			return err
		}
		def, err := _Snail_parseDef(r.Value(_Snail_column_Def))
		if err != nil {
			return err
		}
		totalPower, err := _Snail_parseTotalPower(r.Value(_Snail_column_TotalPower))
		if err != nil {
			return err
		}
		zombieForm, err := _Snail_parseZombieForm(r.Value(_Snail_column_ZombieForm))
		if err != nil {
			return err
		}
		demonForm, err := _Snail_parseDemonForm(r.Value(_Snail_column_DemonForm))
		if err != nil {
			return err
		}
		angelForm, err := _Snail_parseAngelForm(r.Value(_Snail_column_AngelForm))
		if err != nil {
			return err
		}
		mutantForm, err := _Snail_parseMutantForm(r.Value(_Snail_column_MutantForm))
		if err != nil {
			return err
		}
		mechaForm, err := _Snail_parseMechaForm(r.Value(_Snail_column_MechaForm))
		if err != nil {
			return err
		}
		dragonForm, err := _Snail_parseDragonForm(r.Value(_Snail_column_DragonForm))
		if err != nil {
			return err
		}
		speciesWarEssences, err := _Snail_parseSpeciesWarEssences(r.Value(_Snail_column_SpeciesWarEssences))
		if err != nil {
			return err
		}
		minionSimPower, err := _Snail_parseMinionSimPower(r.Value(_Snail_column_MinionSimPower))
		if err != nil {
			return err
		}

		if _, ok := _Snail_cache[playerID][snailID]; ok {
			return &sheetdb.DuplicationError{FieldName: "SnailID"}
		}

		snail := Snail{
			PlayerID:           playerID,
			SnailID:            snailID,
			Updated:            updated,
			SnailName:          snailName,
			Club:               club,
			SWKit:              sWKit,
			SWKitRank:          sWKitRank,
			Server:             server,
			ServerNum:          serverNum,
			Leadership:         leadership,
			Art:                art,
			Fth:                fth,
			Fame:               fame,
			Civ:                civ,
			Tech:               tech,
			Hp:                 hp,
			Atk:                atk,
			Rush:               rush,
			Def:                def,
			TotalPower:         totalPower,
			ZombieForm:         zombieForm,
			DemonForm:          demonForm,
			AngelForm:          angelForm,
			MutantForm:         mutantForm,
			MechaForm:          mechaForm,
			DragonForm:         dragonForm,
			SpeciesWarEssences: speciesWarEssences,
			MinionSimPower:     minionSimPower,
		}

		_Snail_maxRowNo++
		if _, ok := _Snail_cache[snail.PlayerID]; !ok {
			_Snail_cache[snail.PlayerID] = map[int]*Snail{}
			_Snail_rowNoMap[snail.PlayerID] = map[int]int{}
		}
		_Snail_cache[snail.PlayerID][snail.SnailID] = &snail
		_Snail_rowNoMap[snail.PlayerID][snail.SnailID] = _Snail_maxRowNo
	}

	return nil
}

// GetSnail returns a snail by SnailID.
// If it can not be found, this method returns *sheetdb.NotFoundError.
func (m *Player) GetSnail(snailID int) (*Snail, error) {
	_Snail_mutex.RLock()
	defer _Snail_mutex.RUnlock()
	if v, ok := _Snail_cache[m.PlayerID][snailID]; ok {
		return v, nil
	}
	return nil, &sheetdb.NotFoundError{Model: "Snail"}
}

// GetSnail returns a snail by primary keys.
// If it can not be found, this function returns *sheetdb.NotFoundError.
func GetSnail(playerID int, snailID int) (*Snail, error) {
	m, err := GetPlayer(playerID)
	if err != nil {
		return nil, err
	}
	return m.GetSnail(snailID)
}

// SnailQuery is used for selecting snails.
type SnailQuery struct {
	filter func(snail *Snail) bool
	sort   func(snails []*Snail)
}

// SnailQueryOption is an option to change the behavior of SnailQuery.
type SnailQueryOption func(query *SnailQuery) *SnailQuery

// SnailFilter is an option to change the filtering behavior of SnailQuery.
func SnailFilter(filterFunc func(snail *Snail) bool) func(query *SnailQuery) *SnailQuery {
	return func(query *SnailQuery) *SnailQuery {
		if query != nil {
			query.filter = filterFunc
		}
		return query
	}
}

// SnailSort is an option to change the sorting behavior of SnailQuery.
func SnailSort(sortFunc func(snails []*Snail)) func(query *SnailQuery) *SnailQuery {
	return func(query *SnailQuery) *SnailQuery {
		if query != nil {
			query.sort = sortFunc
		}
		return query
	}
}

// GetSnails returns all snails.
// If any options are specified, the result according to the specified option is returned.
// If there are no snail to return, this function returns an nil array.
// If the sort option is not specified, the order of snails is random.
func GetAllSnails(opts ...SnailQueryOption) ([]*Snail, error) {
	query := &SnailQuery{}
	for _, opt := range opts {
		query = opt(query)
	}
	_Snail_mutex.RLock()
	defer _Snail_mutex.RUnlock()
	var snails []*Snail
	if query.filter != nil {
		for _, v := range _Snail_cache {
			for _, w := range v {
				if query.filter(w) {
					snails = append(snails, w)
				}
			}
		}
	} else {
		for _, v := range _Snail_cache {
			for _, w := range v {
				snails = append(snails, w)
			}
		}
	}
	if query.sort != nil {
		query.sort(snails)
	}
	return snails, nil
}

// GetSnails returns all snails that player has.
// If any options are specified, the result according to the specified option is returned.
// If there are no snail to return, this method returns an nil array.
// If the sort option is not specified, the order of snails is random.
func (m *Player) GetSnails(opts ...SnailQueryOption) ([]*Snail, error) {
	query := &SnailQuery{}
	for _, opt := range opts {
		query = opt(query)
	}
	_Snail_mutex.RLock()
	defer _Snail_mutex.RUnlock()
	var snails []*Snail
	if query.filter != nil {
		for _, v := range _Snail_cache[m.PlayerID] {
			if query.filter(v) {
				snails = append(snails, v)
			}
		}
	} else {
		for _, v := range _Snail_cache[m.PlayerID] {
			snails = append(snails, v)
		}
	}
	if query.sort != nil {
		query.sort(snails)
	}
	return snails, nil
}

// GetSnails returns all snails that player has.
// If any options are specified, the result according to the specified option is returned.
// If there are no snail to return, this function returns an nil array.
// If the sort option is not specified, the order of snails is random.
func GetSnails(playerID int, opts ...SnailQueryOption) ([]*Snail, error) {
	m, err := GetPlayer(playerID)
	if err != nil {
		return nil, err
	}
	return m.GetSnails(opts...)
}

// AddSnail adds new snail to player.
// SnailID is generated automatically.
// If any fields are invalid, this method returns error.
func (m *Player) AddSnail(updated int, snailName string, club int, sWKit string, sWKitRank int, server ServerName, serverNum int, leadership int, art int, fth int, fame int, civ int, tech int, hp int, atk int, rush int, def int, totalPower int, zombieForm int, demonForm int, angelForm int, mutantForm int, mechaForm int, dragonForm int, speciesWarEssences int, minionSimPower int) (*Snail, error) {
	_Snail_mutex.Lock()
	defer _Snail_mutex.Unlock()
	if err := _Snail_validateSnailName(snailName); err != nil {
		return nil, err
	}
	if err := _Snail_validateSWKit(sWKit); err != nil {
		return nil, err
	}
	maxID := 0
	for _, v := range _Snail_cache[m.PlayerID] {
		if maxID < v.SnailID {
			maxID = v.SnailID
		}
	}
	snail := &Snail{
		PlayerID:           m.PlayerID,
		SnailID:            maxID + 1,
		Updated:            updated,
		SnailName:          snailName,
		Club:               club,
		SWKit:              sWKit,
		SWKitRank:          sWKitRank,
		Server:             server,
		ServerNum:          serverNum,
		Leadership:         leadership,
		Art:                art,
		Fth:                fth,
		Fame:               fame,
		Civ:                civ,
		Tech:               tech,
		Hp:                 hp,
		Atk:                atk,
		Rush:               rush,
		Def:                def,
		TotalPower:         totalPower,
		ZombieForm:         zombieForm,
		DemonForm:          demonForm,
		AngelForm:          angelForm,
		MutantForm:         mutantForm,
		MechaForm:          mechaForm,
		DragonForm:         dragonForm,
		SpeciesWarEssences: speciesWarEssences,
		MinionSimPower:     minionSimPower,
	}
	if err := snail._asyncAdd(_Snail_maxRowNo + 1); err != nil {
		return nil, err
	}
	_Snail_maxRowNo++
	if _, ok := _Snail_cache[snail.PlayerID]; !ok {
		_Snail_cache[snail.PlayerID] = map[int]*Snail{}
		_Snail_rowNoMap[snail.PlayerID] = map[int]int{}
	}
	_Snail_cache[snail.PlayerID][snail.SnailID] = snail
	_Snail_rowNoMap[snail.PlayerID][snail.SnailID] = _Snail_maxRowNo
	return snail, nil
}

// AddSnail adds new snail to player.
// SnailID is generated automatically.
// If any fields are invalid, this function returns error.
func AddSnail(playerID int, updated int, snailName string, club int, sWKit string, sWKitRank int, server ServerName, serverNum int, leadership int, art int, fth int, fame int, civ int, tech int, hp int, atk int, rush int, def int, totalPower int, zombieForm int, demonForm int, angelForm int, mutantForm int, mechaForm int, dragonForm int, speciesWarEssences int, minionSimPower int) (*Snail, error) {
	m, err := GetPlayer(playerID)
	if err != nil {
		return nil, err
	}
	return m.AddSnail(updated, snailName, club, sWKit, sWKitRank, server, serverNum, leadership, art, fth, fame, civ, tech, hp, atk, rush, def, totalPower, zombieForm, demonForm, angelForm, mutantForm, mechaForm, dragonForm, speciesWarEssences, minionSimPower)
}

// UpdateSnail updates snail.
// If it can not be found, this method returns *sheetdb.NotFoundError.
// If any fields are invalid, this method returns error.
func (m *Player) UpdateSnail(snailID int, updated int, snailName string, club int, sWKit string, sWKitRank int, server ServerName, serverNum int, leadership int, art int, fth int, fame int, civ int, tech int, hp int, atk int, rush int, def int, totalPower int, zombieForm int, demonForm int, angelForm int, mutantForm int, mechaForm int, dragonForm int, speciesWarEssences int, minionSimPower int) (*Snail, error) {
	_Snail_mutex.Lock()
	defer _Snail_mutex.Unlock()
	snail, ok := _Snail_cache[m.PlayerID][snailID]
	if !ok {
		return nil, &sheetdb.NotFoundError{Model: "Snail"}
	}
	if err := _Snail_validateSnailName(snailName); err != nil {
		return nil, err
	}
	if err := _Snail_validateSWKit(sWKit); err != nil {
		return nil, err
	}
	snailCopy := *snail
	snailCopy.Updated = updated
	snailCopy.SnailName = snailName
	snailCopy.Club = club
	snailCopy.SWKit = sWKit
	snailCopy.SWKitRank = sWKitRank
	snailCopy.Server = server
	snailCopy.ServerNum = serverNum
	snailCopy.Leadership = leadership
	snailCopy.Art = art
	snailCopy.Fth = fth
	snailCopy.Fame = fame
	snailCopy.Civ = civ
	snailCopy.Tech = tech
	snailCopy.Hp = hp
	snailCopy.Atk = atk
	snailCopy.Rush = rush
	snailCopy.Def = def
	snailCopy.TotalPower = totalPower
	snailCopy.ZombieForm = zombieForm
	snailCopy.DemonForm = demonForm
	snailCopy.AngelForm = angelForm
	snailCopy.MutantForm = mutantForm
	snailCopy.MechaForm = mechaForm
	snailCopy.DragonForm = dragonForm
	snailCopy.SpeciesWarEssences = speciesWarEssences
	snailCopy.MinionSimPower = minionSimPower
	if err := (&snailCopy)._asyncUpdate(); err != nil {
		return nil, err
	}
	*snail = snailCopy
	return snail, nil
}

// UpdateSnail updates snail.
// If it can not be found, this function returns *sheetdb.NotFoundError.
// If any fields are invalid, this function returns error.
func UpdateSnail(playerID int, snailID int, updated int, snailName string, club int, sWKit string, sWKitRank int, server ServerName, serverNum int, leadership int, art int, fth int, fame int, civ int, tech int, hp int, atk int, rush int, def int, totalPower int, zombieForm int, demonForm int, angelForm int, mutantForm int, mechaForm int, dragonForm int, speciesWarEssences int, minionSimPower int) (*Snail, error) {
	m, err := GetPlayer(playerID)
	if err != nil {
		return nil, err
	}
	return m.UpdateSnail(snailID, updated, snailName, club, sWKit, sWKitRank, server, serverNum, leadership, art, fth, fame, civ, tech, hp, atk, rush, def, totalPower, zombieForm, demonForm, angelForm, mutantForm, mechaForm, dragonForm, speciesWarEssences, minionSimPower)
}

// DeleteSnail deletes snail from player.
// If it can not be found, this method returns *sheetdb.NotFoundError.
func (m *Player) DeleteSnail(snailID int) error {
	_Snail_mutex.Lock()
	defer _Snail_mutex.Unlock()
	snail, ok := _Snail_cache[m.PlayerID][snailID]
	if !ok {
		return &sheetdb.NotFoundError{Model: "Snail"}
	}
	if err := snail._asyncDelete(); err != nil {
		return err
	}
	delete(_Snail_cache[m.PlayerID], snailID)
	return nil
}

// DeleteSnail deletes snail from player.
// If it can not be found, this function returns *sheetdb.NotFoundError.
func DeleteSnail(playerID int, snailID int) error {
	m, err := GetPlayer(playerID)
	if err != nil {
		return err
	}
	return m.DeleteSnail(snailID)
}

func _Snail_validateSnailName(snailName string) error {
	if snailName == "" {
		return &sheetdb.EmptyStringError{FieldName: "SnailName"}
	}
	return nil
}

func _Snail_validateSWKit(sWKit string) error {
	return nil
}

func _Snail_parsePlayerID(playerID string) (int, error) {
	v, err := strconv.Atoi(playerID)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "PlayerID", Err: err}
	}
	return v, nil
}

func _Snail_parseSnailID(snailID string) (int, error) {
	v, err := strconv.Atoi(snailID)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "SnailID", Err: err}
	}
	return v, nil
}

func _Snail_parseUpdated(updated string) (int, error) {
	v, err := strconv.Atoi(updated)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Updated", Err: err}
	}
	return v, nil
}

func _Snail_parseClub(club string) (int, error) {
	v, err := strconv.Atoi(club)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Club", Err: err}
	}
	return v, nil
}

func _Snail_parseSWKitRank(sWKitRank string) (int, error) {
	v, err := strconv.Atoi(sWKitRank)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "SWKitRank", Err: err}
	}
	return v, nil
}

func _Snail_parseServer(server string) (ServerName, error) {
	v, err := NewServerName(server)
	if err != nil {
		return v, &sheetdb.InvalidValueError{FieldName: "Server", Err: err}
	}
	return v, nil
}

func _Snail_parseServerNum(serverNum string) (int, error) {
	v, err := strconv.Atoi(serverNum)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "ServerNum", Err: err}
	}
	return v, nil
}

func _Snail_parseLeadership(leadership string) (int, error) {
	v, err := strconv.Atoi(leadership)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Leadership", Err: err}
	}
	return v, nil
}

func _Snail_parseArt(art string) (int, error) {
	v, err := strconv.Atoi(art)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Art", Err: err}
	}
	return v, nil
}

func _Snail_parseFth(fth string) (int, error) {
	v, err := strconv.Atoi(fth)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Fth", Err: err}
	}
	return v, nil
}

func _Snail_parseFame(fame string) (int, error) {
	v, err := strconv.Atoi(fame)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Fame", Err: err}
	}
	return v, nil
}

func _Snail_parseCiv(civ string) (int, error) {
	v, err := strconv.Atoi(civ)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Civ", Err: err}
	}
	return v, nil
}

func _Snail_parseTech(tech string) (int, error) {
	v, err := strconv.Atoi(tech)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Tech", Err: err}
	}
	return v, nil
}

func _Snail_parseHp(hp string) (int, error) {
	v, err := strconv.Atoi(hp)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Hp", Err: err}
	}
	return v, nil
}

func _Snail_parseAtk(atk string) (int, error) {
	v, err := strconv.Atoi(atk)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Atk", Err: err}
	}
	return v, nil
}

func _Snail_parseRush(rush string) (int, error) {
	v, err := strconv.Atoi(rush)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Rush", Err: err}
	}
	return v, nil
}

func _Snail_parseDef(def string) (int, error) {
	v, err := strconv.Atoi(def)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Def", Err: err}
	}
	return v, nil
}

func _Snail_parseTotalPower(totalPower string) (int, error) {
	v, err := strconv.Atoi(totalPower)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "TotalPower", Err: err}
	}
	return v, nil
}

func _Snail_parseZombieForm(zombieForm string) (int, error) {
	v, err := strconv.Atoi(zombieForm)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "ZombieForm", Err: err}
	}
	return v, nil
}

func _Snail_parseDemonForm(demonForm string) (int, error) {
	v, err := strconv.Atoi(demonForm)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "DemonForm", Err: err}
	}
	return v, nil
}

func _Snail_parseAngelForm(angelForm string) (int, error) {
	v, err := strconv.Atoi(angelForm)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "AngelForm", Err: err}
	}
	return v, nil
}

func _Snail_parseMutantForm(mutantForm string) (int, error) {
	v, err := strconv.Atoi(mutantForm)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "MutantForm", Err: err}
	}
	return v, nil
}

func _Snail_parseMechaForm(mechaForm string) (int, error) {
	v, err := strconv.Atoi(mechaForm)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "MechaForm", Err: err}
	}
	return v, nil
}

func _Snail_parseDragonForm(dragonForm string) (int, error) {
	v, err := strconv.Atoi(dragonForm)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "DragonForm", Err: err}
	}
	return v, nil
}

func _Snail_parseSpeciesWarEssences(speciesWarEssences string) (int, error) {
	v, err := strconv.Atoi(speciesWarEssences)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "SpeciesWarEssences", Err: err}
	}
	return v, nil
}

func _Snail_parseMinionSimPower(minionSimPower string) (int, error) {
	v, err := strconv.Atoi(minionSimPower)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "MinionSimPower", Err: err}
	}
	return v, nil
}

func (m *Snail) _asyncAdd(rowNo int) error {
	data := []gsheets.UpdateValue{
		{
			SheetName: _Snail_sheetName,
			RowNo:     rowNo,
			Values: []interface{}{
				m.PlayerID,
				m.SnailID,
				m.Updated,
				m.SnailName,
				m.Club,
				m.SWKit,
				m.SWKitRank,
				m.Server.String(),
				m.ServerNum,
				m.Leadership,
				m.Art,
				m.Fth,
				m.Fame,
				m.Civ,
				m.Tech,
				m.Hp,
				m.Atk,
				m.Rush,
				m.Def,
				m.TotalPower,
				m.ZombieForm,
				m.DemonForm,
				m.AngelForm,
				m.MutantForm,
				m.MechaForm,
				m.DragonForm,
				m.SpeciesWarEssences,
				m.MinionSimPower,
				time.Now().UTC(),
				"",
			},
		},
	}
	return dbClient.AsyncUpdate(data)
}

func (m *Snail) _asyncUpdate() error {
	data := []gsheets.UpdateValue{
		{
			SheetName: _Snail_sheetName,
			RowNo:     _Snail_rowNoMap[m.PlayerID][m.SnailID],
			Values: []interface{}{
				m.PlayerID,
				m.SnailID,
				m.Updated,
				m.SnailName,
				m.Club,
				m.SWKit,
				m.SWKitRank,
				m.Server.String(),
				m.ServerNum,
				m.Leadership,
				m.Art,
				m.Fth,
				m.Fame,
				m.Civ,
				m.Tech,
				m.Hp,
				m.Atk,
				m.Rush,
				m.Def,
				m.TotalPower,
				m.ZombieForm,
				m.DemonForm,
				m.AngelForm,
				m.MutantForm,
				m.MechaForm,
				m.DragonForm,
				m.SpeciesWarEssences,
				m.MinionSimPower,
				time.Now().UTC(),
				"",
			},
		},
	}
	return dbClient.AsyncUpdate(data)
}

func (m *Snail) _asyncDelete() error {
	now := time.Now().UTC()
	data := []gsheets.UpdateValue{
		{
			SheetName: _Snail_sheetName,
			RowNo:     _Snail_rowNoMap[m.PlayerID][m.SnailID],
			Values: []interface{}{
				m.PlayerID,
				m.SnailID,
				m.Updated,
				m.SnailName,
				m.Club,
				m.SWKit,
				m.SWKitRank,
				m.Server.String(),
				m.ServerNum,
				m.Leadership,
				m.Art,
				m.Fth,
				m.Fame,
				m.Civ,
				m.Tech,
				m.Hp,
				m.Atk,
				m.Rush,
				m.Def,
				m.TotalPower,
				m.ZombieForm,
				m.DemonForm,
				m.AngelForm,
				m.MutantForm,
				m.MechaForm,
				m.DragonForm,
				m.SpeciesWarEssences,
				m.MinionSimPower,
				now,
				now,
			},
		},
	}
	return dbClient.AsyncUpdate(data)
}
