// Code generated by "sheetdb-modeler"; DO NOT EDIT.
// Create a Spreadsheet (sheet name: "players") as data storage.
// The spreadsheet header is as follows:
//   player_id | disco_id | updated_at | deleted_at
// Please copy and paste this header on the first line of the sheet.

package sheetDAO

import (
	"strconv"
	"sync"
	"time"

	"github.com/delve/gsheets"
	"github.com/delve/sheetdb"
)

const (
	// Sheet definition
	_Player_sheetName        = "players"
	_Player_column_PlayerID  = 0 // A
	_Player_column_DiscoId   = 1 // B
	_Player_column_UpdatedAt = 2 // C
	_Player_column_DeletedAt = 3 // D

	// Parent children relation for compile check
	_Player_child_Snail         = 0
	_Player_numOfChildren       = 1
	_Player_numOfDirectChildren = 1
)

var (
	_Player_mutex             = sync.RWMutex{}
	_Player_cache             = map[int]*Player{} // map[playerID]*Player
	_Player_rowNoMap          = map[int]int{}     // map[playerID]rowNo
	_Player_maxRowNo          = 0
	_Player_DiscoId_uniqueMap = map[string]*Player{} // map[discoID]*Player
)

func _() {
	// An "undeclared name" compiler error signifies that parent and child model set names are different.
	// Make sure that all models in parent-child relationship exist in the same model set (spreadsheet) and try again.
	_ = _Snail_modelSetName_default
	// An "undeclared name" compiler error signifies that parent-children option conflicts between models.
	// Make sure that the parent-children options are correct for all relevant models and try again.
	_ = _Snail_parent_Player
	// An "invalid array index" compiler error signifies that the children option is incorrect.
	// Make sure that all child models are specified, including not only the direct child model
	// but also the grandchild model, and try again.
	var x [1]struct{}
	_ = x[_Player_numOfChildren-_Player_numOfDirectChildren-_Snail_numOfChildren]
}

func init() {
	sheetdb.RegisterModel("default", "Player", _Player_sheetName, _Player_load)
}

func _Player_load(data *gsheets.Sheet) error {

	_Player_mutex.Lock()
	defer _Player_mutex.Unlock()

	_Player_cache = map[int]*Player{}
	_Player_rowNoMap = map[int]int{}
	_Player_maxRowNo = 0
	_Player_DiscoId_uniqueMap = map[string]*Player{}

	for i, r := range data.Rows() {
		if i == 0 {
			continue
		}
		if r.Value(_Player_column_DeletedAt) != "" {
			_Player_maxRowNo++
			continue
		}
		if r.Value(_Player_column_PlayerID) == "" {
			break
		}

		playerID, err := _Player_parsePlayerID(r.Value(_Player_column_PlayerID))
		if err != nil {
			return err
		}
		discoID := r.Value(_Player_column_DiscoId)
		if err := _Player_validateDiscoId(discoID, ""); err != nil {
			return err
		}

		if _, ok := _Player_cache[playerID]; ok {
			return &sheetdb.DuplicationError{FieldName: "PlayerID"}
		}

		player := Player{
			PlayerID: playerID,
			DiscoId:  discoID,
		}

		_Player_maxRowNo++
		_Player_cache[player.PlayerID] = &player
		_Player_rowNoMap[player.PlayerID] = _Player_maxRowNo
		_Player_DiscoId_uniqueMap[player.DiscoId] = &player
	}

	return nil
}

// GetPlayer returns a player by PlayerID.
// If it can not be found, this function returns *sheetdb.NotFoundError.
func GetPlayer(playerID int) (*Player, error) {
	_Player_mutex.RLock()
	defer _Player_mutex.RUnlock()
	if v, ok := _Player_cache[playerID]; ok {
		return v, nil
	}
	return nil, &sheetdb.NotFoundError{Model: "Player"}
}

// GetPlayerByDiscoId returns a player by DiscoId.
// If it can not be found, this function returns *sheetdb.NotFoundError.
func GetPlayerByDiscoId(discoID string) (*Player, error) {
	_Player_mutex.RLock()
	defer _Player_mutex.RUnlock()
	if v, ok := _Player_DiscoId_uniqueMap[discoID]; ok {
		return v, nil
	}
	return nil, &sheetdb.NotFoundError{Model: "Player"}
}

// PlayerQuery is used for selecting players.
type PlayerQuery struct {
	filter func(player *Player) bool
	sort   func(players []*Player)
}

// PlayerQueryOption is an option to change the behavior of PlayerQuery.
type PlayerQueryOption func(query *PlayerQuery) *PlayerQuery

// PlayerFilter is an option to change the filtering behavior of PlayerQuery.
func PlayerFilter(filterFunc func(player *Player) bool) func(query *PlayerQuery) *PlayerQuery {
	return func(query *PlayerQuery) *PlayerQuery {
		if query != nil {
			query.filter = filterFunc
		}
		return query
	}
}

// PlayerSort is an option to change the sorting behavior of PlayerQuery.
func PlayerSort(sortFunc func(players []*Player)) func(query *PlayerQuery) *PlayerQuery {
	return func(query *PlayerQuery) *PlayerQuery {
		if query != nil {
			query.sort = sortFunc
		}
		return query
	}
}

// GetPlayers returns all players.
// If any options are specified, the result according to the specified option is returned.
// If there are no player to return, this function returns an nil array.
// If the sort option is not specified, the order of players is random.
func GetAllPlayers(opts ...PlayerQueryOption) ([]*Player, error) {
	query := &PlayerQuery{}
	for _, opt := range opts {
		query = opt(query)
	}
	_Player_mutex.RLock()
	defer _Player_mutex.RUnlock()
	var players []*Player
	if query.filter != nil {
		for _, v := range _Player_cache {
			if query.filter(v) {
				players = append(players, v)
			}
		}
	} else {
		for _, v := range _Player_cache {
			players = append(players, v)
		}
	}
	if query.sort != nil {
		query.sort(players)
	}
	return players, nil
}

// AddPlayer adds new player.
// PlayerID is generated automatically.
// If any fields are invalid, this function returns error.
func AddPlayer(discoID string) (*Player, error) {
	_Player_mutex.Lock()
	defer _Player_mutex.Unlock()
	if err := _Player_validateDiscoId(discoID, ""); err != nil {
		return nil, err
	}
	player := &Player{
		PlayerID: _Player_maxRowNo + 1,
		DiscoId:  discoID,
	}
	if err := player._asyncAdd(_Player_maxRowNo + 1); err != nil {
		return nil, err
	}
	_Player_maxRowNo++
	_Player_cache[player.PlayerID] = player
	_Player_rowNoMap[player.PlayerID] = _Player_maxRowNo
	_Player_DiscoId_uniqueMap[player.DiscoId] = player
	return player, nil
}

// UpdatePlayer updates player.
// If it can not be found, this function returns *sheetdb.NotFoundError.
// If any fields are invalid, this function returns error.
func UpdatePlayer(playerID int, discoID string) (*Player, error) {
	_Player_mutex.Lock()
	defer _Player_mutex.Unlock()
	player, ok := _Player_cache[playerID]
	if !ok {
		return nil, &sheetdb.NotFoundError{Model: "Player"}
	}
	if err := _Player_validateDiscoId(discoID, player.DiscoId); err != nil {
		return nil, err
	}
	playerCopy := *player
	playerCopy.DiscoId = discoID
	if err := (&playerCopy)._asyncUpdate(); err != nil {
		return nil, err
	}
	if playerCopy.DiscoId != player.DiscoId {
		delete(_Player_DiscoId_uniqueMap, player.DiscoId)
	}
	*player = playerCopy
	_Player_DiscoId_uniqueMap[playerCopy.DiscoId] = &playerCopy
	return player, nil
}

// DeletePlayer deletes player and it's children snail.
// If it can not be found, this function returns *sheetdb.NotFoundError.
func DeletePlayer(playerID int) error {
	_Player_mutex.Lock()
	defer _Player_mutex.Unlock()
	_Snail_mutex.Lock()
	defer _Snail_mutex.Unlock()
	player, ok := _Player_cache[playerID]
	if !ok {
		return &sheetdb.NotFoundError{Model: "Player"}
	}
	var snails []*Snail
	for _, v := range _Snail_cache[playerID] {
		snails = append(snails, v)
	}
	if err := player._asyncDelete(snails); err != nil {
		return err
	}
	delete(_Player_cache, playerID)
	delete(_Player_DiscoId_uniqueMap, player.DiscoId)
	delete(_Snail_cache, playerID)
	return nil
}

func _Player_validateDiscoId(discoID string, oldDiscoId string) error {
	if discoID == "" {
		return &sheetdb.EmptyStringError{FieldName: "DiscoId"}
	}
	if discoID != oldDiscoId {
		if _, ok := _Player_DiscoId_uniqueMap[discoID]; ok {
			return &sheetdb.DuplicationError{FieldName: "DiscoId"}
		}
	}
	return nil
}

func _Player_parsePlayerID(playerID string) (int, error) {
	v, err := strconv.Atoi(playerID)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "PlayerID", Err: err}
	}
	return v, nil
}

func (m *Player) _asyncAdd(rowNo int) error {
	data := []gsheets.UpdateValue{
		{
			SheetName: _Player_sheetName,
			RowNo:     rowNo,
			Values: []interface{}{
				m.PlayerID,
				m.DiscoId,
				time.Now().UTC(),
				"",
			},
		},
	}
	return dbClient.AsyncUpdate(data)
}

func (m *Player) _asyncUpdate() error {
	data := []gsheets.UpdateValue{
		{
			SheetName: _Player_sheetName,
			RowNo:     _Player_rowNoMap[m.PlayerID],
			Values: []interface{}{
				m.PlayerID,
				m.DiscoId,
				time.Now().UTC(),
				"",
			},
		},
	}
	return dbClient.AsyncUpdate(data)
}

func (m *Player) _asyncDelete(snails []*Snail) error {
	now := time.Now().UTC()
	data := []gsheets.UpdateValue{
		{
			SheetName: _Player_sheetName,
			RowNo:     _Player_rowNoMap[m.PlayerID],
			Values: []interface{}{
				m.PlayerID,
				m.DiscoId,
				now,
				now,
			},
		},
	}
	for _, v := range snails {
		data = append(data, gsheets.UpdateValue{
			SheetName: _Snail_sheetName,
			RowNo:     _Snail_rowNoMap[v.PlayerID][v.SnailID],
			Values: []interface{}{
				v.PlayerID,
				v.SnailID,
				v.Updated,
				v.SnailName,
				v.Club,
				v.SWKit,
				v.SWKitRank,
				v.Server.String(),
				v.ServerNum,
				v.Leadership,
				v.Art,
				v.Fth,
				v.Fame,
				v.Civ,
				v.Tech,
				v.Hp,
				v.Atk,
				v.Rush,
				v.Def,
				v.TotalPower,
				v.ZombieForm,
				v.DemonForm,
				v.AngelForm,
				v.MutantForm,
				v.MechaForm,
				v.DragonForm,
				v.SpeciesWarEssences,
				v.MinionSimPower,
				now,
				now,
			},
		})
	}
	return dbClient.AsyncUpdate(data)
}
