// Code generated by "sheetdb-modeler"; DO NOT EDIT.
// Create a Spreadsheet (sheet name: "snailStats") as data storage.
// The spreadsheet header is as follows:
//   snail_id | snail_stat_id | updated | leadership | art | fth | fame | civ | tech | hp | atk | rush | def | total_power | zombie_form | demon_form | angel_form | mutant_form | mecha_form | dragon_form | species_war_essences | updated_at | deleted_at
// Please copy and paste this header on the first line of the sheet.

package sheetDAO

import (
	"strconv"
	"sync"
	"time"

	"github.com/delve/gsheets"
	"github.com/delve/sheetdb"
)

const (
	// Sheet definition
	_SnailStat_sheetName                 = "snailStats"
	_SnailStat_column_SnailID            = 0  // A
	_SnailStat_column_SnailStatID        = 1  // B
	_SnailStat_column_Updated            = 2  // C
	_SnailStat_column_Leadership         = 3  // D
	_SnailStat_column_Art                = 4  // E
	_SnailStat_column_Fth                = 5  // F
	_SnailStat_column_Fame               = 6  // G
	_SnailStat_column_Civ                = 7  // H
	_SnailStat_column_Tech               = 8  // I
	_SnailStat_column_Hp                 = 9  // J
	_SnailStat_column_Atk                = 10 // K
	_SnailStat_column_Rush               = 11 // L
	_SnailStat_column_Def                = 12 // M
	_SnailStat_column_TotalPower         = 13 // N
	_SnailStat_column_ZombieForm         = 14 // O
	_SnailStat_column_DemonForm          = 15 // P
	_SnailStat_column_AngelForm          = 16 // Q
	_SnailStat_column_MutantForm         = 17 // R
	_SnailStat_column_MechaForm          = 18 // S
	_SnailStat_column_DragonForm         = 19 // T
	_SnailStat_column_SpeciesWarEssences = 20 // U
	_SnailStat_column_UpdatedAt          = 21 // V
	_SnailStat_column_DeletedAt          = 22 // W

	// Parent children relation for compile check
	_SnailStat_modelSetName_default = 0
	_SnailStat_parent_Snail         = 0
	_SnailStat_numOfChildren        = 0
	_SnailStat_numOfDirectChildren  = 0
)

var (
	_SnailStat_mutex    = sync.RWMutex{}
	_SnailStat_cache    = map[int]map[int]*SnailStat{} // map[snailID][snailStatID]*SnailStat
	_SnailStat_rowNoMap = map[int]map[int]int{}        // map[snailID][snailStatID]rowNo
	_SnailStat_maxRowNo = 0
)

func _() {
	// An "undeclared name" compiler error signifies that parent-children option conflicts between models.
	// Make sure that the parent-children options are correct for all relevant models and try again.
	_ = _Snail_child_SnailStat
}

func init() {
	sheetdb.RegisterModel("default", "SnailStat", _SnailStat_sheetName, _SnailStat_load)
}

func _SnailStat_load(data *gsheets.Sheet) error {

	_SnailStat_mutex.Lock()
	defer _SnailStat_mutex.Unlock()

	_SnailStat_cache = map[int]map[int]*SnailStat{}
	_SnailStat_rowNoMap = map[int]map[int]int{}
	_SnailStat_maxRowNo = 0

	for i, r := range data.Rows() {
		if i == 0 {
			continue
		}
		if r.Value(_SnailStat_column_DeletedAt) != "" {
			_SnailStat_maxRowNo++
			continue
		}
		if r.Value(_SnailStat_column_SnailID) == "" {
			break
		}

		snailID, err := _SnailStat_parseSnailID(r.Value(_SnailStat_column_SnailID))
		if err != nil {
			return err
		}
		snailStatID, err := _SnailStat_parseSnailStatID(r.Value(_SnailStat_column_SnailStatID))
		if err != nil {
			return err
		}
		updated, err := _SnailStat_parseUpdated(r.Value(_SnailStat_column_Updated))
		if err != nil {
			return err
		}
		leadership, err := _SnailStat_parseLeadership(r.Value(_SnailStat_column_Leadership))
		if err != nil {
			return err
		}
		art, err := _SnailStat_parseArt(r.Value(_SnailStat_column_Art))
		if err != nil {
			return err
		}
		fth, err := _SnailStat_parseFth(r.Value(_SnailStat_column_Fth))
		if err != nil {
			return err
		}
		fame, err := _SnailStat_parseFame(r.Value(_SnailStat_column_Fame))
		if err != nil {
			return err
		}
		civ, err := _SnailStat_parseCiv(r.Value(_SnailStat_column_Civ))
		if err != nil {
			return err
		}
		tech, err := _SnailStat_parseTech(r.Value(_SnailStat_column_Tech))
		if err != nil {
			return err
		}
		hp, err := _SnailStat_parseHp(r.Value(_SnailStat_column_Hp))
		if err != nil {
			return err
		}
		atk, err := _SnailStat_parseAtk(r.Value(_SnailStat_column_Atk))
		if err != nil {
			return err
		}
		rush, err := _SnailStat_parseRush(r.Value(_SnailStat_column_Rush))
		if err != nil {
			return err
		}
		def, err := _SnailStat_parseDef(r.Value(_SnailStat_column_Def))
		if err != nil {
			return err
		}
		totalPower, err := _SnailStat_parseTotalPower(r.Value(_SnailStat_column_TotalPower))
		if err != nil {
			return err
		}
		zombieForm, err := _SnailStat_parseZombieForm(r.Value(_SnailStat_column_ZombieForm))
		if err != nil {
			return err
		}
		demonForm, err := _SnailStat_parseDemonForm(r.Value(_SnailStat_column_DemonForm))
		if err != nil {
			return err
		}
		angelForm, err := _SnailStat_parseAngelForm(r.Value(_SnailStat_column_AngelForm))
		if err != nil {
			return err
		}
		mutantForm, err := _SnailStat_parseMutantForm(r.Value(_SnailStat_column_MutantForm))
		if err != nil {
			return err
		}
		mechaForm, err := _SnailStat_parseMechaForm(r.Value(_SnailStat_column_MechaForm))
		if err != nil {
			return err
		}
		dragonForm, err := _SnailStat_parseDragonForm(r.Value(_SnailStat_column_DragonForm))
		if err != nil {
			return err
		}
		speciesWarEssences, err := _SnailStat_parseSpeciesWarEssences(r.Value(_SnailStat_column_SpeciesWarEssences))
		if err != nil {
			return err
		}

		if _, ok := _SnailStat_cache[snailID][snailStatID]; ok {
			return &sheetdb.DuplicationError{FieldName: "SnailStatID"}
		}

		snailStat := SnailStat{
			SnailID:            snailID,
			SnailStatID:        snailStatID,
			Updated:            updated,
			Leadership:         leadership,
			Art:                art,
			Fth:                fth,
			Fame:               fame,
			Civ:                civ,
			Tech:               tech,
			Hp:                 hp,
			Atk:                atk,
			Rush:               rush,
			Def:                def,
			TotalPower:         totalPower,
			ZombieForm:         zombieForm,
			DemonForm:          demonForm,
			AngelForm:          angelForm,
			MutantForm:         mutantForm,
			MechaForm:          mechaForm,
			DragonForm:         dragonForm,
			SpeciesWarEssences: speciesWarEssences,
		}

		_SnailStat_maxRowNo++
		if _, ok := _SnailStat_cache[snailStat.SnailID]; !ok {
			_SnailStat_cache[snailStat.SnailID] = map[int]*SnailStat{}
			_SnailStat_rowNoMap[snailStat.SnailID] = map[int]int{}
		}
		_SnailStat_cache[snailStat.SnailID][snailStat.SnailStatID] = &snailStat
		_SnailStat_rowNoMap[snailStat.SnailID][snailStat.SnailStatID] = _SnailStat_maxRowNo
	}

	return nil
}

// GetSnailStat returns a snailStat by SnailStatID.
// If it can not be found, this method returns *sheetdb.NotFoundError.
func (m *Snail) GetSnailStat(snailStatID int) (*SnailStat, error) {
	_SnailStat_mutex.RLock()
	defer _SnailStat_mutex.RUnlock()
	if v, ok := _SnailStat_cache[m.SnailID][snailStatID]; ok {
		return v, nil
	}
	return nil, &sheetdb.NotFoundError{Model: "SnailStat"}
}

// GetSnailStat returns a snailStat by primary keys.
// If it can not be found, this function returns *sheetdb.NotFoundError.
func GetSnailStat(snailID int, snailStatID int) (*SnailStat, error) {
	m, err := GetSnail(snailID)
	if err != nil {
		return nil, err
	}
	return m.GetSnailStat(snailStatID)
}

// SnailStatQuery is used for selecting snailStats.
type SnailStatQuery struct {
	filter func(snailStat *SnailStat) bool
	sort   func(snailStats []*SnailStat)
}

// SnailStatQueryOption is an option to change the behavior of SnailStatQuery.
type SnailStatQueryOption func(query *SnailStatQuery) *SnailStatQuery

// SnailStatFilter is an option to change the filtering behavior of SnailStatQuery.
func SnailStatFilter(filterFunc func(snailStat *SnailStat) bool) func(query *SnailStatQuery) *SnailStatQuery {
	return func(query *SnailStatQuery) *SnailStatQuery {
		if query != nil {
			query.filter = filterFunc
		}
		return query
	}
}

// SnailStatSort is an option to change the sorting behavior of SnailStatQuery.
func SnailStatSort(sortFunc func(snailStats []*SnailStat)) func(query *SnailStatQuery) *SnailStatQuery {
	return func(query *SnailStatQuery) *SnailStatQuery {
		if query != nil {
			query.sort = sortFunc
		}
		return query
	}
}

// GetSnailStats returns all snailStats that snail has.
// If any options are specified, the result according to the specified option is returned.
// If there are no snailStat to return, this method returns an nil array.
// If the sort option is not specified, the order of snailStats is random.
func (m *Snail) GetSnailStats(opts ...SnailStatQueryOption) ([]*SnailStat, error) {
	query := &SnailStatQuery{}
	for _, opt := range opts {
		query = opt(query)
	}
	_SnailStat_mutex.RLock()
	defer _SnailStat_mutex.RUnlock()
	var snailStats []*SnailStat
	if query.filter != nil {
		for _, v := range _SnailStat_cache[m.SnailID] {
			if query.filter(v) {
				snailStats = append(snailStats, v)
			}
		}
	} else {
		for _, v := range _SnailStat_cache[m.SnailID] {
			snailStats = append(snailStats, v)
		}
	}
	if query.sort != nil {
		query.sort(snailStats)
	}
	return snailStats, nil
}

// GetSnailStats returns all snailStats that snail has.
// If any options are specified, the result according to the specified option is returned.
// If there are no snailStat to return, this function returns an nil array.
// If the sort option is not specified, the order of snailStats is random.
func GetSnailStats(snailID int, opts ...SnailStatQueryOption) ([]*SnailStat, error) {
	m, err := GetSnail(snailID)
	if err != nil {
		return nil, err
	}
	return m.GetSnailStats(opts...)
}

// AddSnailStat adds new snailStat to snail.
// SnailStatID is generated automatically.
// If any fields are invalid, this method returns error.
func (m *Snail) AddSnailStat(updated int, leadership int, art int, fth int, fame int, civ int, tech int, hp int, atk int, rush int, def int, totalPower int, zombieForm int, demonForm int, angelForm int, mutantForm int, mechaForm int, dragonForm int, speciesWarEssences int) (*SnailStat, error) {
	_SnailStat_mutex.Lock()
	defer _SnailStat_mutex.Unlock()
	maxID := 0
	for _, v := range _SnailStat_cache[m.SnailID] {
		if maxID < v.SnailStatID {
			maxID = v.SnailStatID
		}
	}
	snailStat := &SnailStat{
		SnailID:            m.SnailID,
		SnailStatID:        maxID + 1,
		Updated:            updated,
		Leadership:         leadership,
		Art:                art,
		Fth:                fth,
		Fame:               fame,
		Civ:                civ,
		Tech:               tech,
		Hp:                 hp,
		Atk:                atk,
		Rush:               rush,
		Def:                def,
		TotalPower:         totalPower,
		ZombieForm:         zombieForm,
		DemonForm:          demonForm,
		AngelForm:          angelForm,
		MutantForm:         mutantForm,
		MechaForm:          mechaForm,
		DragonForm:         dragonForm,
		SpeciesWarEssences: speciesWarEssences,
	}
	if err := snailStat._asyncAdd(_SnailStat_maxRowNo + 1); err != nil {
		return nil, err
	}
	_SnailStat_maxRowNo++
	if _, ok := _SnailStat_cache[snailStat.SnailID]; !ok {
		_SnailStat_cache[snailStat.SnailID] = map[int]*SnailStat{}
		_SnailStat_rowNoMap[snailStat.SnailID] = map[int]int{}
	}
	_SnailStat_cache[snailStat.SnailID][snailStat.SnailStatID] = snailStat
	_SnailStat_rowNoMap[snailStat.SnailID][snailStat.SnailStatID] = _SnailStat_maxRowNo
	return snailStat, nil
}

// AddSnailStat adds new snailStat to snail.
// SnailStatID is generated automatically.
// If any fields are invalid, this function returns error.
func AddSnailStat(snailID int, updated int, leadership int, art int, fth int, fame int, civ int, tech int, hp int, atk int, rush int, def int, totalPower int, zombieForm int, demonForm int, angelForm int, mutantForm int, mechaForm int, dragonForm int, speciesWarEssences int) (*SnailStat, error) {
	m, err := GetSnail(snailID)
	if err != nil {
		return nil, err
	}
	return m.AddSnailStat(updated, leadership, art, fth, fame, civ, tech, hp, atk, rush, def, totalPower, zombieForm, demonForm, angelForm, mutantForm, mechaForm, dragonForm, speciesWarEssences)
}

// UpdateSnailStat updates snailStat.
// If it can not be found, this method returns *sheetdb.NotFoundError.
// If any fields are invalid, this method returns error.
func (m *Snail) UpdateSnailStat(snailStatID int, updated int, leadership int, art int, fth int, fame int, civ int, tech int, hp int, atk int, rush int, def int, totalPower int, zombieForm int, demonForm int, angelForm int, mutantForm int, mechaForm int, dragonForm int, speciesWarEssences int) (*SnailStat, error) {
	_SnailStat_mutex.Lock()
	defer _SnailStat_mutex.Unlock()
	snailStat, ok := _SnailStat_cache[m.SnailID][snailStatID]
	if !ok {
		return nil, &sheetdb.NotFoundError{Model: "SnailStat"}
	}
	snailStatCopy := *snailStat
	snailStatCopy.Updated = updated
	snailStatCopy.Leadership = leadership
	snailStatCopy.Art = art
	snailStatCopy.Fth = fth
	snailStatCopy.Fame = fame
	snailStatCopy.Civ = civ
	snailStatCopy.Tech = tech
	snailStatCopy.Hp = hp
	snailStatCopy.Atk = atk
	snailStatCopy.Rush = rush
	snailStatCopy.Def = def
	snailStatCopy.TotalPower = totalPower
	snailStatCopy.ZombieForm = zombieForm
	snailStatCopy.DemonForm = demonForm
	snailStatCopy.AngelForm = angelForm
	snailStatCopy.MutantForm = mutantForm
	snailStatCopy.MechaForm = mechaForm
	snailStatCopy.DragonForm = dragonForm
	snailStatCopy.SpeciesWarEssences = speciesWarEssences
	if err := (&snailStatCopy)._asyncUpdate(); err != nil {
		return nil, err
	}
	*snailStat = snailStatCopy
	return snailStat, nil
}

// UpdateSnailStat updates snailStat.
// If it can not be found, this function returns *sheetdb.NotFoundError.
// If any fields are invalid, this function returns error.
func UpdateSnailStat(snailID int, snailStatID int, updated int, leadership int, art int, fth int, fame int, civ int, tech int, hp int, atk int, rush int, def int, totalPower int, zombieForm int, demonForm int, angelForm int, mutantForm int, mechaForm int, dragonForm int, speciesWarEssences int) (*SnailStat, error) {
	m, err := GetSnail(snailID)
	if err != nil {
		return nil, err
	}
	return m.UpdateSnailStat(snailStatID, updated, leadership, art, fth, fame, civ, tech, hp, atk, rush, def, totalPower, zombieForm, demonForm, angelForm, mutantForm, mechaForm, dragonForm, speciesWarEssences)
}

// DeleteSnailStat deletes snailStat from snail.
// If it can not be found, this method returns *sheetdb.NotFoundError.
func (m *Snail) DeleteSnailStat(snailStatID int) error {
	_SnailStat_mutex.Lock()
	defer _SnailStat_mutex.Unlock()
	snailStat, ok := _SnailStat_cache[m.SnailID][snailStatID]
	if !ok {
		return &sheetdb.NotFoundError{Model: "SnailStat"}
	}
	if err := snailStat._asyncDelete(); err != nil {
		return err
	}
	delete(_SnailStat_cache[m.SnailID], snailStatID)
	return nil
}

// DeleteSnailStat deletes snailStat from snail.
// If it can not be found, this function returns *sheetdb.NotFoundError.
func DeleteSnailStat(snailID int, snailStatID int) error {
	m, err := GetSnail(snailID)
	if err != nil {
		return err
	}
	return m.DeleteSnailStat(snailStatID)
}

func _SnailStat_parseSnailID(snailID string) (int, error) {
	v, err := strconv.Atoi(snailID)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "SnailID", Err: err}
	}
	return v, nil
}

func _SnailStat_parseSnailStatID(snailStatID string) (int, error) {
	v, err := strconv.Atoi(snailStatID)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "SnailStatID", Err: err}
	}
	return v, nil
}

func _SnailStat_parseUpdated(updated string) (int, error) {
	v, err := strconv.Atoi(updated)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Updated", Err: err}
	}
	return v, nil
}

func _SnailStat_parseLeadership(leadership string) (int, error) {
	v, err := strconv.Atoi(leadership)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Leadership", Err: err}
	}
	return v, nil
}

func _SnailStat_parseArt(art string) (int, error) {
	v, err := strconv.Atoi(art)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Art", Err: err}
	}
	return v, nil
}

func _SnailStat_parseFth(fth string) (int, error) {
	v, err := strconv.Atoi(fth)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Fth", Err: err}
	}
	return v, nil
}

func _SnailStat_parseFame(fame string) (int, error) {
	v, err := strconv.Atoi(fame)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Fame", Err: err}
	}
	return v, nil
}

func _SnailStat_parseCiv(civ string) (int, error) {
	v, err := strconv.Atoi(civ)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Civ", Err: err}
	}
	return v, nil
}

func _SnailStat_parseTech(tech string) (int, error) {
	v, err := strconv.Atoi(tech)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Tech", Err: err}
	}
	return v, nil
}

func _SnailStat_parseHp(hp string) (int, error) {
	v, err := strconv.Atoi(hp)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Hp", Err: err}
	}
	return v, nil
}

func _SnailStat_parseAtk(atk string) (int, error) {
	v, err := strconv.Atoi(atk)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Atk", Err: err}
	}
	return v, nil
}

func _SnailStat_parseRush(rush string) (int, error) {
	v, err := strconv.Atoi(rush)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Rush", Err: err}
	}
	return v, nil
}

func _SnailStat_parseDef(def string) (int, error) {
	v, err := strconv.Atoi(def)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "Def", Err: err}
	}
	return v, nil
}

func _SnailStat_parseTotalPower(totalPower string) (int, error) {
	v, err := strconv.Atoi(totalPower)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "TotalPower", Err: err}
	}
	return v, nil
}

func _SnailStat_parseZombieForm(zombieForm string) (int, error) {
	v, err := strconv.Atoi(zombieForm)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "ZombieForm", Err: err}
	}
	return v, nil
}

func _SnailStat_parseDemonForm(demonForm string) (int, error) {
	v, err := strconv.Atoi(demonForm)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "DemonForm", Err: err}
	}
	return v, nil
}

func _SnailStat_parseAngelForm(angelForm string) (int, error) {
	v, err := strconv.Atoi(angelForm)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "AngelForm", Err: err}
	}
	return v, nil
}

func _SnailStat_parseMutantForm(mutantForm string) (int, error) {
	v, err := strconv.Atoi(mutantForm)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "MutantForm", Err: err}
	}
	return v, nil
}

func _SnailStat_parseMechaForm(mechaForm string) (int, error) {
	v, err := strconv.Atoi(mechaForm)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "MechaForm", Err: err}
	}
	return v, nil
}

func _SnailStat_parseDragonForm(dragonForm string) (int, error) {
	v, err := strconv.Atoi(dragonForm)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "DragonForm", Err: err}
	}
	return v, nil
}

func _SnailStat_parseSpeciesWarEssences(speciesWarEssences string) (int, error) {
	v, err := strconv.Atoi(speciesWarEssences)
	if err != nil {
		return 0, &sheetdb.InvalidValueError{FieldName: "SpeciesWarEssences", Err: err}
	}
	return v, nil
}

func (m *SnailStat) _asyncAdd(rowNo int) error {
	data := []gsheets.UpdateValue{
		{
			SheetName: _SnailStat_sheetName,
			RowNo:     rowNo,
			Values: []interface{}{
				m.SnailID,
				m.SnailStatID,
				m.Updated,
				m.Leadership,
				m.Art,
				m.Fth,
				m.Fame,
				m.Civ,
				m.Tech,
				m.Hp,
				m.Atk,
				m.Rush,
				m.Def,
				m.TotalPower,
				m.ZombieForm,
				m.DemonForm,
				m.AngelForm,
				m.MutantForm,
				m.MechaForm,
				m.DragonForm,
				m.SpeciesWarEssences,
				time.Now().UTC(),
				"",
			},
		},
	}
	return dbClient.AsyncUpdate(data)
}

func (m *SnailStat) _asyncUpdate() error {
	data := []gsheets.UpdateValue{
		{
			SheetName: _SnailStat_sheetName,
			RowNo:     _SnailStat_rowNoMap[m.SnailID][m.SnailStatID],
			Values: []interface{}{
				m.SnailID,
				m.SnailStatID,
				m.Updated,
				m.Leadership,
				m.Art,
				m.Fth,
				m.Fame,
				m.Civ,
				m.Tech,
				m.Hp,
				m.Atk,
				m.Rush,
				m.Def,
				m.TotalPower,
				m.ZombieForm,
				m.DemonForm,
				m.AngelForm,
				m.MutantForm,
				m.MechaForm,
				m.DragonForm,
				m.SpeciesWarEssences,
				time.Now().UTC(),
				"",
			},
		},
	}
	return dbClient.AsyncUpdate(data)
}

func (m *SnailStat) _asyncDelete() error {
	now := time.Now().UTC()
	data := []gsheets.UpdateValue{
		{
			SheetName: _SnailStat_sheetName,
			RowNo:     _SnailStat_rowNoMap[m.SnailID][m.SnailStatID],
			Values: []interface{}{
				m.SnailID,
				m.SnailStatID,
				m.Updated,
				m.Leadership,
				m.Art,
				m.Fth,
				m.Fame,
				m.Civ,
				m.Tech,
				m.Hp,
				m.Atk,
				m.Rush,
				m.Def,
				m.TotalPower,
				m.ZombieForm,
				m.DemonForm,
				m.AngelForm,
				m.MutantForm,
				m.MechaForm,
				m.DragonForm,
				m.SpeciesWarEssences,
				now,
				now,
			},
		},
	}
	return dbClient.AsyncUpdate(data)
}
